// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzVXitX3i5kyZUYKzJkFQ50wnZSlwelJY',
    appId: '1:962919884438:web:0fb8af14e9151b48e704b7',
    messagingSenderId: '962919884438',
    projectId: 'driverhub-partners-prod',
    authDomain: 'driverhub-partners-prod.firebaseapp.com',
    storageBucket: 'driverhub-partners-prod.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVkwzglFWeNM52HgiKf8njj6WEA9VWr04',
    appId: '1:962919884438:android:3cfbd71414a1c102e704b7',
    messagingSenderId: '962919884438',
    projectId: 'driverhub-partners-prod',
    storageBucket: 'driverhub-partners-prod.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9UI259dv9UBi-b8Rb1RMX3Web93GmQG4',
    appId: '1:962919884438:ios:06f5461adde7160fe704b7',
    messagingSenderId: '962919884438',
    projectId: 'driverhub-partners-prod',
    storageBucket: 'driverhub-partners-prod.appspot.com',
    iosBundleId: 'com.driverHubPartner.app',
  );
}
