// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYfOddphQ_rObfPt2AWSlPi7pZ1uYsq14',
    appId: '1:555320798074:web:a69e454443676cc376c4c3',
    messagingSenderId: '555320798074',
    projectId: 'driverhub-partners-sandbox',
    authDomain: 'driverhub-partners-sandbox.firebaseapp.com',
    storageBucket: 'driverhub-partners-sandbox.appspot.com',
    measurementId: 'G-X1E0TLEP5V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAm39SN5ePhLE3G71TkJTfm7-7EqhWz7o',
    appId: '1:555320798074:android:57a787aa6500aadf76c4c3',
    messagingSenderId: '555320798074',
    projectId: 'driverhub-partners-sandbox',
    storageBucket: 'driverhub-partners-sandbox.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC85aAOHz2T8ze91vWj4sXolXQ86oF3YPg',
    appId: '1:555320798074:ios:54b0edefac0daa1f76c4c3',
    messagingSenderId: '555320798074',
    projectId: 'driverhub-partners-sandbox',
    storageBucket: 'driverhub-partners-sandbox.appspot.com',
    iosBundleId: 'com.example.driverHubPartner',
  );
}
